"use client";

import { useState } from "react";
import type { ExplainPayload } from "@/lib/llm/explain";

// Requests a plain-English rationale from /api/explain. Works with or without
// an Anthropic API key (server falls back to a templated explanation).
export function ExplainButton({ payload }: { payload: ExplainPayload }) {
  const [loading, setLoading] = useState(false);
  const [text, setText] = useState<string | null>(null);
  const [source, setSource] = useState<string | null>(null);

  async function run() {
    setLoading(true);
    try {
      const res = await fetch("/api/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });
      const data = await res.json();
      setText(data.text ?? data.error ?? "No explanation.");
      setSource(data.source ?? null);
    } catch {
      setText("Couldn't generate an explanation.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="mt-3">
      <button
        onClick={run}
        disabled={loading}
        className="pill bg-ink text-white hover:opacity-90 disabled:opacity-50"
      >
        {loading ? "Thinking…" : "Explain this"}
      </button>
      {text ? (
        <div className="mt-2 rounded-md bg-slate-50 p-3 text-sm text-slate-700">
          {text}
          {source ? (
            <div className="mt-1 text-[11px] text-slate-400">
              {source === "llm" ? "Generated by Claude" : "Templated summary (no API key set)"}
            </div>
          ) : null}
        </div>
      ) : null}
    </div>
  );
}
